name: flutter_web
description: Flutter 内部 HTTP Server 示例
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.4
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_multipart: ^2.0.1
  mime: ^1.0.0
  http: ^1.1.0
  webview_flutter: ^4.13.0
  url_launcher: ^6.1.10
  qr_flutter: ^4.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true